server {
    listen 80;

    # If updating here, also update api/dev.sh and web/nuxt.config.ts

    location /api/countries/ {
        proxy_pass http://host.docker.internal:8787;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
    }

    location /api/doodle/ {
        proxy_pass http://host.docker.internal:8788;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
    }

    location /api/network-status {
        proxy_pass http://host.docker.internal:8789;
        proxy_set_header Host $host;
    }

    location = /resume.pdf {
        proxy_pass http://host.docker.internal:8790;
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://host.docker.internal:3000;
        proxy_set_header Host $host;
    }
}
