name: Build and Test web

on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
      - 'api/**'
      - 'shared/**'
      - 'package.json'
      - 'package-lock.json'
      - 'playwright.config.ts'
      - '.github/workflows/build-web.yml'
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'api/**'
      - 'shared/**'
      - 'package.json'
      - 'package-lock.json'
      - 'playwright.config.ts'
      - '.github/workflows/build-web.yml'

jobs:
  build:
    name: Build and lint the web project
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        name: Set up Node.js
        with:
          node-version: 24
      
      - name: Install dependencies
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint the code
        run: npm run lint
        working-directory: web

      - name: Type-check the code
        run: npm run typecheck
        working-directory: web

      - name: Build the project
        run: npm run build
        working-directory: web

  playwright:
    name: Playwright E2E Tests
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        name: Set up Node.js
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Playwright
        run: npm exec playwright install

      - name: Run Playwright tests
        run: CI=1 npm test

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7

      - name: Run Chromatic
        uses: chromaui/action@1db61b73b7919508ee8e62336f04bd0aed6da756 # v17.4.1
        with:
          playwright: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          autoAcceptChanges: ${{ github.event_name == 'push' }}
        env:
          CHROMATIC_ARCHIVE_LOCATION: ./test-results
