name: Playwright Acceptance Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
      - development

jobs:
  test:
    timeout-minutes: 10
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Install Playwright
      run: npx playwright install --with-deps chromium firefox webkit
    - name: Run Playwright tests
      run: CI=1 yarn run test
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
        retention-days: 7
